#pragma once
// a simple listing of all the day headers.

#include "Day.h"
#include "Day01.h"
#include "Day02.h"
#include "Day03.h"
#include "Day04.h"
#include "Day05.h"
#include "Day06.h"
#include "Day07.h"
#include "Day08.h"
#include "Day09.h"
#include "Day10.h"
#include "Day11.h"
#include "Day12.h"
#include "Day13.h"
#include "Day14.h"
#include "Day15.h"
#include "Day16.h"
#include "Day17.h"
#include "Day18.h"
#include "Day19.h"
// #include "Day20.h"
// #include "Day21.h"
// #include "Day22.h"
// #include "Day23.h"
// #include "Day24.h"
// #include "Day25.h"


